### ISSUE TITLE
Initialize endpoint fails with unhandled error

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#133]
**Describe the bug**
Provider fails with unhandled error

**To Reproduce**
https://provider.rinkeby.oceanprotocol.com/api/v1/services/initialize?documentId=did:op:08A814050DBC4DA746B3b608FaC1C72d13d01f4C&serviceId=1&serviceType=access&dataToken=0x08A814050DBC4DA746B3b608FaC1C72d13d01f4C&consumerAddress=0x4D156A2ef69ffdDC55838176C6712C90f60a2285

** Output **
HTTP 500
{"error":"HTTPSConnectionPool(host='ipfs.io', port=443): Read timed out. (read timeout=3)"}

** Logs **
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: loading config file /ocean-provider/config.ini
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ network = rinkeby
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ artifacts.path = /ocean-provider/artifacts
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ aquarius.url = https://aquarius.mp.rinkeby.v3.dev-ocean.com/
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ operator_service.url = https://nextv.operator.oceanprotocol.io
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ allow_non_public_ip = False
2021-04-26 07:28:56 provider-99d8655cc-lrfbk root[10] DEBUG Metadata Store connected at https://aquarius.mp.rinkeby.v3.dev-ocean.com/
2021-04-26 07:28:56 provider-99d8655cc-lrfbk root[10] DEBUG Metadata Store API documentation at https://aquarius.mp.rinkeby.v3.dev-ocean.com//api/v1/docs
2021-04-26 07:28:56 provider-99d8655cc-lrfbk root[10] DEBUG Metadata assets at https://aquarius.mp.rinkeby.v3.dev-ocean.com//api/v1/aquarius/assets
2021-04-26 07:28:56 provider-99d8655cc-lrfbk urllib3.connectionpool[10] DEBUG Starting new HTTPS connection (1): aquarius.mp.rinkeby.v3.dev-ocean.com:443
2021-04-26 07:28:56 provider-99d8655cc-lrfbk urllib3.connectionpool[10] DEBUG https://aquarius.mp.rinkeby.v3.dev-ocean.com:443 "GET //api/v1/aquarius/assets/ddo/did:op:08A814050DBC4DA746B3b608FaC1C72d13d01f4C HTTP/1.1" 200 None
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: loading config file /ocean-provider/config.ini
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ network = rinkeby
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ artifacts.path = /ocean-provider/artifacts
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ aquarius.url = https://aquarius.mp.rinkeby.v3.dev-ocean.com/
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ operator_service.url = https://nextv.operator.oceanprotocol.io
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ allow_non_public_ip = False
2021-04-26 07:28:56,189 - ocean_provider.util - INFO - Connecting through Osmosis to generate the signed url.
2021-04-26 07:28:56 provider-99d8655cc-lrfbk Osmosis[10] INFO Loading `on_premise` driver, url=https://ipfs.io/ipfs/QmPZAkggjvEiLQLLxfu2VTFDhdEX1AKQQ1AoJZbtgeCqgZ?filename=chn.log.1.
2021-04-26 07:28:56 provider-99d8655cc-lrfbk Osmosis[10] INFO Loading `on_premise` driver, url=https://ipfs.io/ipfs/QmPZAkggjvEiLQLLxfu2VTFDhdEX1AKQQ1AoJZbtgeCqgZ?filename=chn.log.1.
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: loading config file /ocean-provider/config.ini
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ network = rinkeby
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ artifacts.path = /ocean-provider/artifacts
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ aquarius.url = https://aquarius.mp.rinkeby.v3.dev-ocean.com/
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ operator_service.url = https://nextv.operator.oceanprotocol.io
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ allow_non_public_ip = False
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: loading config file /ocean-provider/config.ini
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ network = rinkeby
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ artifacts.path = /ocean-provider/artifacts
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ aquarius.url = https://aquarius.mp.rinkeby.v3.dev-ocean.com/
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ operator_service.url = https://nextv.operator.oceanprotocol.io
2021-04-26 07:28:56 provider-99d8655cc-lrfbk config[10] DEBUG Config: setting environ allow_non_public_ip = False
2021-04-26 07:28:56 provider-99d8655cc-lrfbk urllib3.connectionpool[10] DEBUG Starting new HTTPS connection (1): ipfs.io:443
2021-04-26 07:28:56 provider-99d8655cc-lrfbk urllib3.connectionpool[10] DEBUG https://ipfs.io:443 "OPTIONS /ipfs/QmPZAkggjvEiLQLLxfu2VTFDhdEX1AKQQ1AoJZbtgeCqgZ?filename=chn.log.1 HTTP/1.1" 200 0
2021-04-26 07:28:56 provider-99d8655cc-lrfbk urllib3.connectionpool[10] DEBUG Starting new HTTPS connection (1): ipfs.io:443
2021-04-26 07:28:59,331 - ocean_provider.routes.consume - ERROR - Error: HTTPSConnectionPool(host='ipfs.io', port=443): Read timed out. (read timeout=3). 
Payload was: ImmutableMultiDict([('documentId', 'did:op:08A814050DBC4DA746B3b608FaC1C72d13d01f4C'), ('serviceId', '1'), ('serviceType', 'access'), ('dataToken', '0x08A814050DBC4DA746B3b608FaC1C72d13d01f4C'), ('consumerAddress', '0x4D156A2ef69ffdDC55838176C6712C90f60a2285')])
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='ipfs.io', port=443): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ocean-provider/ocean_provider/routes/consume.py", line 275, in initialize
    valid, _ = check_url_details(download_url)
  File "/ocean-provider/ocean_provider/util_url.py", line 136, in check_url_details
    result, extra_data = _get_result_from_url(url, with_checksum=with_checksum)
  File "/ocean-provider/ocean_provider/util_url.py", line 176, in _get_result_from_url
    return requests.get(url, stream=True, timeout=REQUEST_TIMEOUT), {}
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='ipfs.io', port=443): Read timed out. (read timeout=3)

**Comment by mihaisc** [comment]
Actual dataset can be found here https://market.oceanprotocol.com/asset/did:op:08A814050DBC4DA746B3b608FaC1C72d13d01f4C (rinkeby)
