### ISSUE TITLE
Random timeouts

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/provider#159]
While testing provider on rinkeby i often get timeout for like 1 minute and this it's back on. There are multiple errors in the logs, not sure if related. During this time the pods were up and running. 

```
2021-06-15 13:11:27,711 - ocean_provider.myapp - ERROR - Exception on /api/v1/services/fileinfo [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_sieve/validator.py", line 81, in wrapper
    return fn(*args, **kwargs)
  File "/ocean-provider/ocean_provider/routes/consume.py", line 177, in fileinfo
    url_list = get_asset_download_urls(
  File "/ocean-provider/ocean_provider/utils/util.py", line 171, in get_asset_download_urls
    return [get_download_url(url, config_file) for url in get_asset_urls(asset, wallet)]
TypeError: 'NoneType' object is not iterable
```

Consistently getting this on polygon as well

![image](https://user-images.githubusercontent.com/26000280/122065045-4d758e80-cdfa-11eb-84b9-0485a0f51f34.png)

**Comment by kremalicious** [comment]
This is also 1 of 2 reasons the ocean.js integration tests fail sometime, which looks like as if the `fileinfo` endpoint just crashed:

<img width="821" alt="Screen Shot 2021-06-22 at 14 50 14" src="https://user-images.githubusercontent.com/90316/122927431-29213100-d369-11eb-8366-c23fea38750d.png">

**Comment by mihaisc** [comment]
@kremalicious i suggest commenting those tests until this is fixed.

**Comment by calina-c** [comment]
Closed after fileinfo fixes cf. @mihaisc.
