### ISSUE TITLE
Provider fails to keep track of nonce

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/provider#266]
Currently, there is an issue with the provider not keeping track of the nonce properly. This causes publishing to fail.

On the frontend, the user will just see an error saying "Publishing DDO failed"

![1 2021-12-02_14-54](https://user-images.githubusercontent.com/20739535/144425410-256e5591-18f3-489e-9213-a043d8ecd20f.png)

Here are the logs associated with the error:

<details>
  <summary>Logs 1</summary>
  
```
2021-12-02 10:44:18 provider-7bd8bd94f4-vxsf8 urllib3.connectionpool[11] DEBUG https://nextv.operator.oceanprotocol.com:443 "GET /api/v1/operator/compute?providerAddress=0x00c6A0BC5cD0078d6Cd0b659E8061B404cfa5704&owner=0xBE5449a6A97aD46c
8558A3356267Ee5D2731ab5e&jobId=15a0aff68baa405dac2c8a3f7ef9d052&documentId=did%3Aop%3A2D0790745479A30eACc4424d35529ef0997E544c&providerSignature=0x225b87272b81573be55f10bff5b6cc349f2e522dcd95f2a3270d6edebdac59095466b33288f257980e3dd0f116
072129e421379e1e22d8a1bc5e97563ccf3c6b1c HTTP/1.1" 200 483 
2021-12-02 10:44:18,965 - ocean_provider.routes.compute - ERROR - Payload was: signature=0x9371b61814ca5715c7791c89bf41e0521a8fce27bf3ad61feed38a761d251d72637265d875cce12c5dcde7bb7b6e26cd5599c73968bc8dfe837fabc7d74bb30c1c,documentId=did:
op:2D0790745479A30eACc4424d35529ef0997E544c,consumerAddress=0xBE5449a6A97aD46c8558A3356267Ee5D2731ab5e,jobId=15a0aff68baa405dac2c8a3f7ef9d052 
Traceback (most recent call last): 
 File "/ocean-provider/ocean_provider/routes/compute.py", line 232, in computeStatus 
   owner, data.get("signature"), original_msg, get_nonce(owner) 
 File "/ocean-provider/ocean_provider/user_nonce.py", line 18, in get_nonce 
   result = models.UserNonce.query.filter_by(address=address).first() 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3429, in first 
   ret = list(self[0:1]) 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__ 
   return list(res) 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3535, in __iter__ 
   return self._execute_and_instances(context) 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances 
   conn = self._get_bind_args( 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args 
   return fn( 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session 
   conn = self.session.connection(**kw) 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1142, in connection 
   return self._connection_for_bind( 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1150, in _connection_for_bind 
   return self.transaction._connection_for_bind( 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind 
   self._assert_active() 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 289, in _assert_active 
   raise sa_exc.InvalidRequestError( 
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.
IntegrityError) UNIQUE constraint failed: user_nonce.address 
[SQL: INSERT INTO user_nonce (address, nonce) VALUES (?, ?)] 
[parameters: ('0x2eCA8718b2fCaf0CF9E150ad4B44EE8c54473D2C', 1)] 
(Background on this error at: http://sqlalche.me/e/13/gkpj) (Background on this error at: http://sqlalche.me/e/13/7s2a) 
2021-12-02 10:44:25,022 - ocean_provider.run - INFO - root endpoint called
```
</details>

<details>
  <summary>Logs 2</summary>
  
  2021-12-02 10:44:26,212 - ocean_provider.myapp - ERROR - Exception on /api/v1/services/nonce [GET] 
Traceback (most recent call last): 
 File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app 
   response = self.full_dispatch_request() 
 File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request 
   rv = self.handle_user_exception(e) 
 File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function 
   return cors_after_request(app.make_response(f(*args, **kwargs))) 
 File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception 
   reraise(exc_type, exc_value, tb) 
 File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise 
   raise value 
 File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request 
   rv = self.dispatch_request() 
 File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request 
   return self.view_functions[rule.endpoint](**req.view_args) 
 File "/usr/local/lib/python3.8/dist-packages/flask_sieve/validator.py", line 81, in wrapper 
   return fn(*args, **kwargs) 
 File "/ocean-provider/ocean_provider/routes/consume.py", line 66, in nonce 
   nonce = get_nonce(address) 
 File "/ocean-provider/ocean_provider/user_nonce.py", line 18, in get_nonce 
   result = models.UserNonce.query.filter_by(address=address).first() 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3429, in first 
   ret = list(self[0:1]) 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__ 
   return list(res) 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3535, in __iter__ 
   return self._execute_and_instances(context) 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances 
   conn = self._get_bind_args( 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args 
   return fn( 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session 
   conn = self.session.connection(**kw) 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1142, in connection 
   return self._connection_for_bind( 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1150, in _connection_for_bind 
   return self.transaction._connection_for_bind( 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind 
   self._assert_active() 
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 289, in _assert_active 
   raise sa_exc.InvalidRequestError( 
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.
IntegrityError) UNIQUE constraint failed: user_nonce.address 
[SQL: INSERT INTO user_nonce (address, nonce) VALUES (?, ?)] 
[parameters: ('0x2eCA8718b2fCaf0CF9E150ad4B44EE8c54473D2C', 1)] 
(Background on this error at: http://sqlalche.me/e/13/gkpj) (Background on this error at: http://sqlalche.me/e/13/7s2a)
</details>

**Comment by DMats** [comment]
CC @alexcos20 

I'm confused. The error seems to indicate we're inserting an address into the user_nonce table that already exists.

```
UNIQUE constraint failed: user_nonce.address 
[SQL: INSERT INTO user_nonce (address, nonce) VALUES (?, ?)] 
[parameters: ('0x2eCA8718b2fCaf0CF9E150ad4B44EE8c54473D2C', 1)] 
```

Yet, the error isn't printed until we try to query the table.

```
 File "/ocean-provider/ocean_provider/user_nonce.py", line 18, in get_nonce 
   result = models.UserNonce.query.filter_by(address=address).first()
```

Furthermore, the `consumerAddress` passed into the `compute` endpoint doesn't match the error address.

(edited for brevity)
```
2021-12-02 10:44:18,965 - ocean_provider.routes.compute - ERROR - Payload was: ...
consumerAddress=0xBE5449a6A97aD46c8558A3356267Ee5D2731ab5e
```

Is it possible this error occurs but is not printed until the *next* time we interact with the UserNonce table? In which case, I'm wondering what 

I'm suspicious of the `encrypt` endpoint since it appears in the screenshot from @jamiehewitt15 and is one of the places where `increment_nonce` is called, but I've got to set this task aside for about an hour. I'll be back to it later today.

**Comment by alexcos20** [comment]
all this because the insert query fails and we do not treat the error by reverting. and thus sqlite remains stuck in a rollback transaction, and it will complain at the next query.

Action item: check all sql results and rollback at errors
