### ISSUE TITLE
Can't publish a dataset hosted on Azure

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/provider#356]
## Describe the bug
There seems to be an issue publishing a data asset that is hosted on Azure.  

## To Reproduce
1. Go to https://market.oceanprotocol.com/publish
2. Try and publish this dataset: https://pandemicdatalake.blob.core.windows.net/public/curated/covid-19/bing_covid-19_data/latest/bing_covid-19_data.csv
4. See error 500 in console

## Screenshots
![provider publish error - 2022-02-10_10-51](https://user-images.githubusercontent.com/20739535/153363839-fe34e9df-bcd7-4ee4-bdaf-d2954c3f7a91.png)

## Screen recording
https://www.loom.com/share/3e2ec2ac85324d83b8285a659f1bc109

## Logs
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_sieve/validator.py", line 81, in wrapper
    return fn(*args, **kwargs)
  File "/ocean-provider/ocean_provider/routes/consume.py", line 186, in fileinfo
    url_list = [get_download_url(url, app.config["PROVIDER_CONFIG_FILE"])]
  File "/ocean-provider/ocean_provider/utils/util.py", line 191, in get_download_url
    osm = Osmosis(url, config_file)
  File "/usr/local/lib/python3.8/dist-packages/osmosis_driver_interface/osmosis.py", line 30, in __init__
    self.computing_plugin = start_plugin(COMPUTING, self.parse_url(url), config_file_path)
  File "/usr/local/lib/python3.8/dist-packages/osmosis_driver_interface/utils.py", line 69, in start_plugin
    plugin_instance = load_plugin(_type, module, config)
  File "/usr/local/lib/python3.8/dist-packages/osmosis_driver_interface/utils.py", line 87, in load_plugin
    return mod.Plugin(config)
  File "/usr/local/lib/python3.8/dist-packages/osmosis_azure_driver/computing_plugin.py", line 37, in __init__
    raise OsmosisError
osmosis_driver_interface.exceptions.OsmosisError
```
## Potential solutiion

Remove osmosis

**Comment by jamiehewitt15** [comment]
Reopening as the same issue still seems to be happening

**Comment by jamiehewitt15** [comment]
This issue only seems to be happening in the V3 Market. I tested in the V4 market preview and it's working fine

**Comment by jamiehewitt15** [comment]
This is now fixed
