### ISSUE TITLE
V4 Provider fails at initialize

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#367]
2022-02-12 14:53:36 fa03c838972f ocean_provider.run[18] INFO incoming request = http, GET, 172.15.0.1, /api/services/initialize?documentId=did:op:749ee33d4fdf1e4c5572c04f75fd3591e48bc8bff3b486904c47d81addf77569&serviceId=notAnId&fileIndex=0&consumerAddress=0xBE5449a6A97aD46c8558A3356267Ee5D2731ab5e&environment=ocean-compute&validUntil=1644677676641
2022-02-12 14:53:36 fa03c838972f ocean_provider.routes.consume[18] INFO initialize called. arguments = ImmutableMultiDict([('documentId', 'did:op:749ee33d4fdf1e4c5572c04f75fd3591e48bc8bff3b486904c47d81addf77569'), ('serviceId', 'notAnId'), ('fileIndex', '0'), ('consumerAddress', '0xBE5449a6A97aD46c8558A3356267Ee5D2731ab5e'), ('environment', 'ocean-compute'), ('validUntil', '1644677676641')])

2022-02-12 14:53:36 fa03c838972f config[18] INFO Config: setting environ operator_service.url = http://172.15.0.13:31000/
2022-02-12 14:53:36 fa03c838972f config[18] INFO Config: setting environ allow_non_public_ip = False
2022-02-12 14:53:36 fa03c838972f ocean_provider.run[18] ERROR error: year 54087 is out of range, payload: b''
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1[936](https://github.com/oceanprotocol/ocean.js/runs/5167952673?check_suite_focus=true#step:13:936), in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_sieve/validator.py", line 81, in wrapper
    return fn(*args, **kwargs)
  File "/ocean-provider/ocean_provider/routes/consume.py", line 199, in initialize
    "providerFee": get_provider_fees(
  File "/ocean-provider/ocean_provider/utils/provider_fees.py", line 37, in get_provider_fees
    provider_fee_amount = get_provider_fee_amount(
  File "/ocean-provider/ocean_provider/utils/provider_fees.py", line 94, in get_provider_fee_amount
    seconds = (datetime.fromtimestamp(valid_until) - datetime.now()).seconds
ValueError: year 54087 is out of range

Value sent by ocean.js seems fine:   1644677676641  
Assuming that this timestamp is in milliseconds:
GMT: Saturday, February 12, 2022 2:54:36.641 PM
Your time zone: Saturday, February 12, 2022 4:54:36.641 PM [GMT+02:00](https://www.epochconverter.com/timezones?q=1644677676641)
Relative: 9 minutes ago

PS: This was observed during ocean.js tests:  https://github.com/oceanprotocol/ocean.js/runs/5167952673?check_suite_focus=true#step:13:935

**Comment by alexcos20** [comment]
Removed critical because ocean.js was sending the timestamp in miliseconds, not in seconds.
Nevertheless , we should have a graceful error instead of untreated exception
