### ISSUE TITLE
Provider crashes if endpoint is not found

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider#423]
2022-04-14 14:11:55 provider-76c8cd647c-7jtg8 ocean_provider.run[14] INFO incoming request = http, GET, 10.18.2.84, /favicon.ico?
2022-04-14 14:11:55 provider-76c8cd647c-7jtg8 ocean_provider.run[14] ERROR error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again., payload: b''
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/usr/local/lib/python3.8/dist-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by calina-c** [comment]
@alexcos20 I worked on trying to reproduce this and nothing seems to be working. I tried:
- variations of GET/POST with this exact same URL or different ones that are not found. I used both regular params and mismatched ones, binary and normal payload etc.
- managed to reproduce the exact same log, still provider does not break, it handles the error gracefully
- identified that it shouldn't depend on the URL itself, since the error handler just manipulates the error itself, not anything related to the IP etc.

I simply can not reproduce this in a test. Can you please let me know where this log is snipped from? (the network, if you remember). Or any other details that might help. E.g. have you seen this more times? Do we have any idea who is sending this request and details wrt headers and other aspects?
