### ISSUE TITLE
Download fails on polygon

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/provider#544]
The download fails for this [asset](https://market.oceanprotocol.com/asset/did:op:0dac5eb4965fb2b485181671adbf3a23b0133abf71d2775eda8043e8efc92d19)

Full log:
```
2022-10-05 12:45:07 | ValueError: sender of order transaction is not the consumer/payer.
-- | --
  |   | 2022-10-05 12:45:07 | raise ValueError("sender of order transaction is not the consumer/payer.")
  |   | 2022-10-05 12:45:07 | File "/ocean-provider/ocean_provider/utils/datatoken.py", line 225, in verify_order_tx
  |   | 2022-10-05 12:45:07 | tx, order_event, provider_fees_event, start_order_tx_id = verify_order_tx(
  |   | 2022-10-05 12:45:07 | File "/ocean-provider/ocean_provider/utils/datatoken.py", line 260, in validate_order
  |   | 2022-10-05 12:45:07 | _tx, _order_log, _, _ = validate_order(
  |   | 2022-10-05 12:45:07 | File "/ocean-provider/ocean_provider/routes/consume.py", line 292, in download
  |   | 2022-10-05 12:45:07 | Traceback (most recent call last):
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc ocean_provider.routes.consume[13] ERROR =Order with tx_id 0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8 could not be validated due to error: sender of order transaction is not the consumer/payer.
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc ocean_provider.utils.datatoken[13] DEBUG verify_order_tx: service timeout = 604800, timestamp delta = 69.97583794593811
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc ocean_provider.utils.datatoken[13] DEBUG Got events log when searching for OrderStarted : (AttributeDict({'args': AttributeDict({'consumer': '0x99840Df5Cb42faBE0Feb8811Aaa4BC99cA6C84e0', 'publishMarketAddress': '0x9984b2453eC7D99a73A5B3a46Da81f197B753C8d', 'payer': '0x99840Df5Cb42faBE0Feb8811Aaa4BC99cA6C84e0', 'amount': 1000000000000000000, 'serviceIndex': 0, 'timestamp': 1664963038, 'blockNumber': 33956781}), 'event': 'OrderStarted', 'logIndex': 115, 'transactionIndex': 29, 'transactionHash': HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8'), 'address': '0x6BEd18159C9a979e050e71702Df2F934051A6a55', 'blockHash': HexBytes('0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd'), 'blockNumber': 33956781}),)
  |   | 2022-10-05 12:45:07 | warnings.warn(
  |   | 2022-10-05 12:45:07 | /usr/local/lib/python3.8/dist-packages/web3/contract.py:1166: UserWarning: The log with transaction hash: HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8') and logIndex: 118 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.
  |   | 2022-10-05 12:45:07 | warnings.warn(
  |   | 2022-10-05 12:45:07 | /usr/local/lib/python3.8/dist-packages/web3/contract.py:1166: UserWarning: The log with transaction hash: HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8') and logIndex: 117 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.
  |   | 2022-10-05 12:45:07 | warnings.warn(
  |   | 2022-10-05 12:45:07 | /usr/local/lib/python3.8/dist-packages/web3/contract.py:1166: UserWarning: The log with transaction hash: HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8') and logIndex: 116 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.
  |   | 2022-10-05 12:45:07 | warnings.warn(
  |   | 2022-10-05 12:45:07 | /usr/local/lib/python3.8/dist-packages/web3/contract.py:1166: UserWarning: The log with transaction hash: HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8') and logIndex: 114 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.
  |   | 2022-10-05 12:45:07 | warnings.warn(
  |   | 2022-10-05 12:45:07 | /usr/local/lib/python3.8/dist-packages/web3/contract.py:1166: UserWarning: The log with transaction hash: HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8') and logIndex: 113 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.
  |   | 2022-10-05 12:45:07 | warnings.warn(
  |   | 2022-10-05 12:45:07 | /usr/local/lib/python3.8/dist-packages/web3/contract.py:1166: UserWarning: The log with transaction hash: HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8') and logIndex: 112 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc ocean_provider.utils.datatoken[13] DEBUG Search for orderStarted in tx_receipt : AttributeDict({'blockHash': HexBytes('0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd'), 'blockNumber': 33956781, 'contractAddress': None, 'cumulativeGasUsed': 5437711, 'effectiveGasPrice': 45000000024, 'from': '0x99840Df5Cb42faBE0Feb8811Aaa4BC99cA6C84e0', 'gasUsed': 112212, 'logs': [AttributeDict({'address': '0x6BEd18159C9a979e050e71702Df2F934051A6a55', 'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'), HexBytes('0x0000000000000000000000000000000000000000000000000000000000000000'), HexBytes('0x000000000000000000000000257fe2e49530a4b7fc3ed597465e2931db3f20b7')], 'data': '0x0000000000000000000000000000000000000000000000000de0b6b3a7640000', 'blockNumber': 33956781, 'transactionHash': HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8'), 'transactionIndex': 29, 'blockHash': HexBytes('0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd'), 'logIndex': 112, 'removed': False}), AttributeDict({'address': '0x257fe2e49530A4B7FC3Ed597465e2931db3f20b7', 'topics': [HexBytes('0x63e223ff524bd93d4cbff98ef34405b39f63ded87f5a8d85e39ccda966f13543'), HexBytes('0x0000000000000000000000006bed18159c9a979e050e71702df2f934051a6a55'), HexBytes('0x00000000000000000000000099840df5cb42fabe0feb8811aaa4bc99ca6c84e0')], 'data': '0x0000000000000000000000000000000000000000000000000de0b6b3a7640000', 'blockNumber': 33956781, 'transactionHash': HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8'), 'transactionIndex': 29, 'blockHash': HexBytes('0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd'), 'logIndex': 113, 'removed': False}), AttributeDict({'address': '0x6BEd18159C9a979e050e71702Df2F934051A6a55', 'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'), HexBytes('0x000000000000000000000000257fe2e49530a4b7fc3ed597465e2931db3f20b7'), HexBytes('0x00000000000000000000000099840df5cb42fabe0feb8811aaa4bc99ca6c84e0')], 'data': '0x0000000000000000000000000000000000000000000000000de0b6b3a7640000', 'blockNumber': 33956781, 'transactionHash': HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8'), 'transactionIndex': 29, 'blockHash': HexBytes('0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd'), 'logIndex': 114, 'removed': False}), AttributeDict({'address': '0x6BEd18159C9a979e050e71702Df2F934051A6a55', 'topics': [HexBytes('0xe1c4fa794edfa8f619b8257a077398950357b9c6398528f94480307352f9afcc'), HexBytes('0x00000000000000000000000099840df5cb42fabe0feb8811aaa4bc99ca6c84e0'), HexBytes('0x0000000000000000000000009984b2453ec7d99a73a5b3a46da81f197b753c8d')], 'data': '0x00000000000000000000000099840df5cb42fabe0feb8811aaa4bc99ca6c84e00000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000633d51de00000000000000000000000000000000000000000000000000000000020623ad', 'blockNumber': 33956781, 'transactionHash': HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8'), 'transactionIndex': 29, 'blockHash': HexBytes('0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd'), 'logIndex': 115, 'removed': False}), AttributeDict({'address': '0x6BEd18159C9a979e050e71702Df2F934051A6a55', 'topics': [HexBytes('0xf8ed11cdaaf10eca2b6c941fb802cb8682afe86cac1eb93f70d0780fa062c544'), HexBytes('0x000000000000000000000000c96ed22751ef6be3e2432118b944a0cdaede10e8'), HexBytes('0x000000000000000000000000282d8efce846a88b159800bd4130ad77443fa1a1')], 'data': '0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000001ce9aca4d4495a5ca535caa9644e55f0ec40b925db4347961492387c6511acb0770a4e73a2db1e9b57bb955917dc4f3488edad2220f6ef81bed8c78dac81b7dcd6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000147b22656e7669726f6e6d656e74223a6e756c6c7d000000000000000000000000', 'blockNumber': 33956781, 'transactionHash': HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8'), 'transactionIndex': 29, 'blockHash': HexBytes('0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd'), 'logIndex': 116, 'removed': False}), AttributeDict({'address': '0x6BEd18159C9a979e050e71702Df2F934051A6a55', 'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'), HexBytes('0x00000000000000000000000099840df5cb42fabe0feb8811aaa4bc99ca6c84e0'), HexBytes('0x0000000000000000000000000000000000000000000000000000000000000000')], 'data': '0x0000000000000000000000000000000000000000000000000de0b6b3a7640000', 'blockNumber': 33956781, 'transactionHash': HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8'), 'transactionIndex': 29, 'blockHash': HexBytes('0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd'), 'logIndex': 117, 'removed': False}), AttributeDict({'address': '0x0000000000000000000000000000000000001010', 'topics': [HexBytes('0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63'), HexBytes('0x0000000000000000000000000000000000000000000000000000000000001010'), HexBytes('0x00000000000000000000000099840df5cb42fabe0feb8811aaa4bc99ca6c84e0'), HexBytes('0x000000000000000000000000e77bbfd8ed65720f187efdd109e38d75eaca7385')], 'data': '0x0000000000000000000000000000000000000000000000000011f087a606a44c00000000000000000000000000000000000000000000000040f9c66039a8d3ab00000000000000000000000000000000000000000000004d4075e0b4120635b800000000000000000000000000000000000000000000000040e7d5d893a22f5f00000000000000000000000000000000000000000000004d4087d13bb80cda04', 'blockNumber': 33956781, 'transactionHash': HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8'), 'transactionIndex': 29, 'blockHash': HexBytes('0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd'), 'logIndex': 118, 'removed': False})], 'logsBloom': HexBytes('0x0000000000000000000000000000000000008000000000000000000000000000000000000000000200008800000400000041c400004040000000000000040000000000000000000000000008000001800000000000000080000110000000040000000000020000000000000000000800000000200000040080000010000000000000000000000000000400000000800000000020000000100000000000000000200000002000000000000060000000000000000000000000000000000020004000000002000080080001000000000000000000004000000050130000002020000000000000000020000000000000000008000000000000000000000000100000'), 'status': 1, 'to': '0x6BEd18159C9a979e050e71702Df2F934051A6a55', 'transactionHash': HexBytes('0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8'), 'transactionIndex': 29, 'type': '0x2'})
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc ocean_provider.utils.datatoken[13] DEBUG Got events log when searching for ReuseOrder : ()
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc web3.providers.HTTPProvider[13] DEBUG Getting response HTTP. URI: https://matic.getblock.io/mainnet/?api_key=, Method: eth_getTransactionReceipt, Response: {'jsonrpc': '2.0', 'id': 34497, 'result': {'blockHash': '0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd', 'blockNumber': '0x20623ad', 'contractAddress': None, 'cumulativeGasUsed': '0x52f90f', 'effectiveGasPrice': '0xa7a358218', 'from': '0x99840df5cb42fabe0feb8811aaa4bc99ca6c84e0', 'gasUsed': '0x1b654', 'logs': [{'address': '0x6bed18159c9a979e050e71702df2f934051a6a55', 'topics': ['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef', '0x0000000000000000000000000000000000000000000000000000000000000000', '0x000000000000000000000000257fe2e49530a4b7fc3ed597465e2931db3f20b7'], 'data': '0x0000000000000000000000000000000000000000000000000de0b6b3a7640000', 'blockNumber': '0x20623ad', 'transactionHash': '0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8', 'transactionIndex': '0x1d', 'blockHash': '0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd', 'logIndex': '0x70', 'removed': False}, {'address': '0x257fe2e49530a4b7fc3ed597465e2931db3f20b7', 'topics': ['0x63e223ff524bd93d4cbff98ef34405b39f63ded87f5a8d85e39ccda966f13543', '0x0000000000000000000000006bed18159c9a979e050e71702df2f934051a6a55', '0x00000000000000000000000099840df5cb42fabe0feb8811aaa4bc99ca6c84e0'], 'data': '0x0000000000000000000000000000000000000000000000000de0b6b3a7640000', 'blockNumber': '0x20623ad', 'transactionHash': '0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8', 'transactionIndex': '0x1d', 'blockHash': '0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd', 'logIndex': '0x71', 'removed': False}, {'address': '0x6bed18159c9a979e050e71702df2f934051a6a55', 'topics': ['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef', '0x000000000000000000000000257fe2e49530a4b7fc3ed597465e2931db3f20b7', '0x00000000000000000000000099840df5cb42fabe0feb8811aaa4bc99ca6c84e0'], 'data': '0x0000000000000000000000000000000000000000000000000de0b6b3a7640000', 'blockNumber': '0x20623ad', 'transactionHash': '0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8', 'transactionIndex': '0x1d', 'blockHash': '0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd', 'logIndex': '0x72', 'removed': False}, {'address': '0x6bed18159c9a979e050e71702df2f934051a6a55', 'topics': ['0xe1c4fa794edfa8f619b8257a077398950357b9c6398528f94480307352f9afcc', '0x00000000000000000000000099840df5cb42fabe0feb8811aaa4bc99ca6c84e0', '0x0000000000000000000000009984b2453ec7d99a73a5b3a46da81f197b753c8d'], 'data': '0x00000000000000000000000099840df5cb42fabe0feb8811aaa4bc99ca6c84e00000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000633d51de00000000000000000000000000000000000000000000000000000000020623ad', 'blockNumber': '0x20623ad', 'transactionHash': '0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8', 'transactionIndex': '0x1d', 'blockHash': '0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd', 'logIndex': '0x73', 'removed': False}, {'address': '0x6bed18159c9a979e050e71702df2f934051a6a55', 'topics': ['0xf8ed11cdaaf10eca2b6c941fb802cb8682afe86cac1eb93f70d0780fa062c544', '0x000000000000000000000000c96ed22751ef6be3e2432118b944a0cdaede10e8', '0x000000000000000000000000282d8efce846a88b159800bd4130ad77443fa1a1'], 'data': '0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000001ce9aca4d4495a5ca535caa9644e55f0ec40b925db4347961492387c6511acb0770a4e73a2db1e9b57bb955917dc4f3488edad2220f6ef81bed8c78dac81b7dcd6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000147b22656e7669726f6e6d656e74223a6e756c6c7d000000000000000000000000', 'blockNumber': '0x20623ad', 'transactionHash': '0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8', 'transactionIndex': '0x1d', 'blockHash': '0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd', 'logIndex': '0x74', 'removed': False}, {'address': '0x6bed18159c9a979e050e71702df2f934051a6a55', 'topics': ['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef', '0x00000000000000000000000099840df5cb42fabe0feb8811aaa4bc99ca6c84e0', '0x0000000000000000000000000000000000000000000000000000000000000000'], 'data': '0x0000000000000000000000000000000000000000000000000de0b6b3a7640000', 'blockNumber': '0x20623ad', 'transactionHash': '0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8', 'transactionIndex': '0x1d', 'blockHash': '0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd', 'logIndex': '0x75', 'removed': False}, {'address': '0x0000000000000000000000000000000000001010', 'topics': ['0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63', '0x0000000000000000000000000000000000000000000000000000000000001010', '0x00000000000000000000000099840df5cb42fabe0feb8811aaa4bc99ca6c84e0', '0x000000000000000000000000e77bbfd8ed65720f187efdd109e38d75eaca7385'], 'data': '0x0000000000000000000000000000000000000000000000000011f087a606a44c00000000000000000000000000000000000000000000000040f9c66039a8d3ab00000000000000000000000000000000000000000000004d4075e0b4120635b800000000000000000000000000000000000000000000000040e7d5d893a22f5f00000000000000000000000000000000000000000000004d4087d13bb80cda04', 'blockNumber': '0x20623ad', 'transactionHash': '0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8', 'transactionIndex': '0x1d', 'blockHash': '0x2b89c8339f3c6b1a3c42d74748c31778823d7dd5fe4c3caa0b8cf4ec5983ecdd', 'logIndex': '0x76', 'removed': False}], 'logsBloom': '0x0000000000000000000000000000000000008000000000000000000000000000000000000000000200008800000400000041c400004040000000000000040000000000000000000000000008000001800000000000000080000110000000040000000000020000000000000000000800000000200000040080000010000000000000000000000000000400000000800000000020000000100000000000000000200000002000000000000060000000000000000000000000000000000020004000000002000080080001000000000000000000004000000050130000002020000000000000000020000000000000000008000000000000000000000000100000', 'status': '0x1', 'to': '0x6bed18159c9a979e050e71702df2f934051a6a55', 'transactionHash': '0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8', 'transactionIndex': '0x1d', 'type': '0x2'}}
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc urllib3.connectionpool[13] DEBUG https://matic.getblock.io:443 "POST /mainnet/?api_key= HTTP/1.1" 200 1126
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc web3.providers.HTTPProvider[13] DEBUG Making request HTTP. URI: https://matic.getblock.io/mainnet/?api_key=, Method: eth_getTransactionReceipt
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc web3.RequestManager[13] DEBUG Making request. Method: eth_getTransactionReceipt
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc ocean_provider.utils.datatoken[13] DEBUG validate_order is on trial 1 in 3.
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc web3.providers.HTTPProvider[13] DEBUG Getting response HTTP. URI: https://matic.getblock.io/mainnet/?api_key=, Method: eth_call, Response: {'jsonrpc': '2.0', 'id': 34496, 'result': '0x0000000000000000000000000000000000000000000000000000000000000001'}
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc urllib3.connectionpool[13] DEBUG https://matic.getblock.io:443 "POST /mainnet/?api_key= HTTP/1.1" 200 71
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc urllib3.connectionpool[13] DEBUG Starting new HTTPS connection (1557): matic.getblock.io:443
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc web3.providers.HTTPProvider[13] DEBUG Making request HTTP. URI: https://matic.getblock.io/mainnet/?api_key=, Method: eth_call
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc web3.providers.HTTPProvider[13] DEBUG Making request HTTP. URI: https://matic.getblock.io/mainnet/?api_key=, Method: eth_call
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc web3.RequestManager[13] DEBUG Making request. Method: eth_call
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc ocean_provider.utils.datatoken[13] DEBUG validate_order: did=did:op:0dac5eb4965fb2b485181671adbf3a23b0133abf71d2775eda8043e8efc92d19, service_id=8e2e09fd9b02e0b7e9c0d0e01c6f500e2a07aa305c04144ad96babf50b820c87, tx_id=0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8, sender=0x99840df5cb42fabe0feb8811aaa4bc99ca6c84e0, num_tokens=1, token_address=0x6BEd18159C9a979e050e71702Df2F934051A6a55
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc ocean_provider.routes.consume[13] INFO validate_order called from download endpoint.
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc urllib3.connectionpool[13] DEBUG https://v4.aquarius.oceanprotocol.com:443 "GET //api/aquarius/assets/ddo/did:op:0dac5eb4965fb2b485181671adbf3a23b0133abf71d2775eda8043e8efc92d19 HTTP/1.1" 200 3915
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc urllib3.connectionpool[13] DEBUG Starting new HTTPS connection (1): v4.aquarius.oceanprotocol.com:443
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc config[13] DEBUG Config: setting environ allow_non_public_ip = False
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc config[13] DEBUG Config: setting environ operator_service.url = https://stagev4.c2d.oceanprotocol.com/
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc config[13] DEBUG Config: setting environ aquarius.url = https://v4.aquarius.oceanprotocol.com/
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc config[13] DEBUG Config: setting environ network = https://matic.getblock.io/mainnet/?api_key=
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc config[13] DEBUG Config: loading config file /ocean-provider/config.ini
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc ocean_provider.routes.consume[13] INFO download called. arguments = ImmutableMultiDict([('fileIndex', '0'), ('documentId', 'did:op:0dac5eb4965fb2b485181671adbf3a23b0133abf71d2775eda8043e8efc92d19'), ('transferTxId', '0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8'), ('serviceId', '8e2e09fd9b02e0b7e9c0d0e01c6f500e2a07aa305c04144ad96babf50b820c87'), ('consumerAddress', '0x99840df5cb42fabe0feb8811aaa4bc99ca6c84e0'), ('nonce', '1664963104779'), ('signature', '0xec82b98a7b7b374b69f59ce790de54920c77acba7cd240889680acb31cfada6c2218f887f8a420edd787207407baa7f0380e4f377452966746ac2f4bea8075aa1b')])
  |   | 2022-10-05 12:45:07 | 2022-10-05 09:45:07 provider-5dff67b9db-ffrrc ocean_provider.run[13] INFO incoming request = http, HEAD, 10.18.89.113, /api/services/download?fileIndex=0&documentId=did:op:0dac5eb4965fb2b485181671adbf3a23b0133abf71d2775eda8043e8efc92d19&transferTxId=0x4fa429393aad134a497b05848ab8ebb7ee6fa20868d69a8da11175f95e46b1d8&serviceId=8e2e09fd9b02e0b7e9c0d0e01c6f500e2a07aa305c04144ad96babf50b820c87&consumerAddress=0x99840df5cb42fabe0feb8811aaa4bc99ca6c84e0&nonce=1664963104779&signature=0xec82b98a7b7b374b69f59ce790de54920c77acba7cd240889680acb31cfada6c2218f887f8a420edd787207407baa7f0380e4f377452966746ac2f4bea8075aa1b
```

Managed to download it after some time, but the error is not relevant. We don't know why it failed

**Comment by trentmc** [comment]
This issue is 5 months old. Is it resolved, perhaps via work elsewhere? Or, if we haven't we seen this issue recently, we can probably close. cc @mihaisc

**Comment by calina-c** [comment]
I agree. @mihaisc
