### ISSUE TITLE
Unify and streamline contract address handling

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/provider#56]
## Expected Behavior

Package should work on Conda as well as PIP

## Current Behavior

`test_commit_access_requested` fails due to not finding the contract *abi* files. The files are located for PIP but not Conda. 

## Failure Information (for bugs)

```
E           ValueError: {'message': 'Attempting to run transaction which calls a contract function, but recipient address 0x35735202cEB9C97b1A823D458C347A993bD49d87 is not a contract address', 'code': -32000, 'data': {'stack': 'r: Attempting to run transaction which calls a contract function, but recipient address 0x35735202cEB9C97b1A823D458C347A993bD49d87 is not a contract address\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:77083\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:67771\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:30:126629\n    at e.exports.i.getCode (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:123698)\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:30:126579\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:50739\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:54500\n    at Object.return (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:54077)\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:52329\n    at e (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:54448)\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:54459\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:51541\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)', 'name': 'r'}}

```

### Possible Solution

Generally the handling of contracts is not as well supported in web3.py (vs. ie. web3 for javascript!). Ideally, the contracts should be returned directly from on-chain (from i.e. the running docker image, or the test/mainnets), and no hard-coding should be necessary.

**Comment by eruizgar91** [comment]
Closed by #23
