### ISSUE TITLE
Add support for sepolia network

### ISSUE THREAD

**Issue by bogdanfazakas** [oceanprotocol/provider#650]
We need to add sepolia chainId as a supported network. I'm getting the following error when trying to encrypt an asset in the publish flow.: Unconfigured chain_id

```
2023-07-17 08:05:23 | 2023-07-17 05:05:23 provider-554997b79d-bbdw2 ocean_provider.routes.encrypt[12] ERROR Failed to encrypt.
-- | --
2023-07-17 08:05:23 | Traceback (most recent call last):
2023-07-17 08:05:23 | File "/ocean-provider/ocean_provider/routes/encrypt.py", line 77, in _encrypt
2023-07-17 08:05:23 | provider_wallet = get_provider_wallet(chain_id)
2023-07-17 08:05:23 | File "/ocean-provider/ocean_provider/utils/basics.py", line 107, in get_provider_wallet
2023-07-17 08:05:23 | pk = get_provider_private_key(chain_id)
2023-07-17 08:05:23 | File "/ocean-provider/ocean_provider/utils/basics.py", line 90, in get_provider_private_key
2023-07-17 08:05:23 | return get_value_from_decoded_env(chain_id, "PROVIDER_PRIVATE_KEY")
2023-07-17 08:05:23 | File "/ocean-provider/ocean_provider/utils/basics.py", line 43, in get_value_from_decoded_env
2023-07-17 08:05:23 | raise Exception("Unconfigured chain_id")
2023-07-17 08:05:23 | Exception: Unconfigured chain_id
```

**Comment by AnaLoznianu** [comment]
@md00ux For sepolia integration that is planed for this week, let's update the deployment to support it as well.

**Comment by bogdanfazakas** [comment]
provider now working fine with sepolia thanks @md00ux
